# Generated by Django 4.2.7 on 2025-12-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apointment',
            new_name='Appointment',
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
    ]
